"""fragrance similar table

Revision ID: 0bc62b8b93d0
Revises: 186ce7492ee7
Create Date: 2025-06-08 21:14:31.332023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc62b8b93d0'
down_revision: Union[str, None] = '186ce7492ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar fragrance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_that_similar_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['fragrance_that_similar_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similar fragrance_fragrance_id'), 'similar fragrance', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_similar fragrance_fragrance_that_similar_id'), 'similar fragrance', ['fragrance_that_similar_id'], unique=False)
    op.create_index(op.f('ix_similar fragrance_user_id'), 'similar fragrance', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_similar fragrance_user_id'), table_name='similar fragrance')
    op.drop_index(op.f('ix_similar fragrance_fragrance_that_similar_id'), table_name='similar fragrance')
    op.drop_index(op.f('ix_similar fragrance_fragrance_id'), table_name='similar fragrance')
    op.drop_table('similar fragrance')
    # ### end Alembic commands ###
