"""add longevity, sillage and price_value vote tables

Revision ID: 186ce7492ee7
Revises: ae2678a6ea79
Create Date: 2025-06-07 01:30:56.677445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186ce7492ee7'
down_revision: Union[str, None] = 'ae2678a6ea79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragrance_longevity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_id', sa.BigInteger(), nullable=False),
    sa.Column('longevity', sa.Enum('very_weak', 'weak', 'moderate', 'long_lasting', 'eternal', name='longevity'), nullable=False),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fragrance_id', name='unique_user_fragrance_longevity')
    )
    op.create_index(op.f('ix_fragrance_longevity_fragrance_id'), 'fragrance_longevity', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_fragrance_longevity_user_id'), 'fragrance_longevity', ['user_id'], unique=False)
    op.create_table('fragrance_prive_value',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_id', sa.BigInteger(), nullable=False),
    sa.Column('price_value', sa.Enum('way_overpriced', 'overpriced', 'ok', 'good_value', 'great_value', name='pricevalue'), nullable=False),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fragrance_id', name='unique_user_fragrance_price_value')
    )
    op.create_index(op.f('ix_fragrance_prive_value_fragrance_id'), 'fragrance_prive_value', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_fragrance_prive_value_user_id'), 'fragrance_prive_value', ['user_id'], unique=False)
    op.create_table('fragrance_sillage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_id', sa.BigInteger(), nullable=False),
    sa.Column('sillage', sa.Enum('intimate', 'moderate', 'strong', 'enormous', name='sillage'), nullable=False),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fragrance_id', name='unique_user_fragrance_sillage')
    )
    op.create_index(op.f('ix_fragrance_sillage_fragrance_id'), 'fragrance_sillage', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_fragrance_sillage_user_id'), 'fragrance_sillage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fragrance_sillage_user_id'), table_name='fragrance_sillage')
    op.drop_index(op.f('ix_fragrance_sillage_fragrance_id'), table_name='fragrance_sillage')
    op.drop_table('fragrance_sillage')
    op.drop_index(op.f('ix_fragrance_prive_value_user_id'), table_name='fragrance_prive_value')
    op.drop_index(op.f('ix_fragrance_prive_value_fragrance_id'), table_name='fragrance_prive_value')
    op.drop_table('fragrance_prive_value')
    op.drop_index(op.f('ix_fragrance_longevity_user_id'), table_name='fragrance_longevity')
    op.drop_index(op.f('ix_fragrance_longevity_fragrance_id'), table_name='fragrance_longevity')
    op.drop_table('fragrance_longevity')
    # ### end Alembic commands ###
