"""add gender vote for fragrance

Revision ID: 1c3ad2de10be
Revises: 741bd4757124
Create Date: 2025-06-05 18:13:10.542508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3ad2de10be'
down_revision: Union[str, None] = '741bd4757124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragrance_gender',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_id', sa.BigInteger(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'mostly_male', 'female', 'mostly_female', 'unisex', name='gender'), nullable=False),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fragrance_id', name='unique_user_fragrance_gender')
    )
    op.create_index(op.f('ix_fragrance_gender_fragrance_id'), 'fragrance_gender', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_fragrance_gender_user_id'), 'fragrance_gender', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fragrance_gender_user_id'), table_name='fragrance_gender')
    op.drop_index(op.f('ix_fragrance_gender_fragrance_id'), table_name='fragrance_gender')
    op.drop_table('fragrance_gender')
    # ### end Alembic commands ###
