"""unique constraint add

Revision ID: 4937a4ff634d
Revises: 1c3ad2de10be
Create Date: 2025-06-06 15:24:41.317456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4937a4ff634d'
down_revision: Union[str, None] = '1c3ad2de10be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_fragrance_note', 'fragrance_note', ['fragrance_id', 'note_id'])
    op.drop_constraint('unique_user_fragrance', 'user_fragrance', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_fragrance', 'user_fragrance', ['user_id', 'fragrance_id'])
    op.drop_constraint('unique_fragrance_note', 'fragrance_note', type_='unique')
    # ### end Alembic commands ###
