"""change table name

Revision ID: 57f728dab596
Revises: 0bc62b8b93d0
Create Date: 2025-06-09 17:04:00.936244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f728dab596'
down_revision: Union[str, None] = '0bc62b8b93d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_fragrance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_that_similar_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['fragrance_that_similar_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similar_fragrance_fragrance_id'), 'similar_fragrance', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_similar_fragrance_fragrance_that_similar_id'), 'similar_fragrance', ['fragrance_that_similar_id'], unique=False)
    op.create_index(op.f('ix_similar_fragrance_user_id'), 'similar_fragrance', ['user_id'], unique=False)
    op.drop_index('ix_similar fragrance_fragrance_id', table_name='similar fragrance')
    op.drop_index('ix_similar fragrance_fragrance_that_similar_id', table_name='similar fragrance')
    op.drop_index('ix_similar fragrance_user_id', table_name='similar fragrance')
    op.drop_table('similar fragrance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar fragrance',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('fragrance_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('fragrance_that_similar_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], name='similar fragrance_fragrance_id_fkey'),
    sa.ForeignKeyConstraint(['fragrance_that_similar_id'], ['fragrance.id'], name='similar fragrance_fragrance_that_similar_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='similar fragrance_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='similar fragrance_pkey')
    )
    op.create_index('ix_similar fragrance_user_id', 'similar fragrance', ['user_id'], unique=False)
    op.create_index('ix_similar fragrance_fragrance_that_similar_id', 'similar fragrance', ['fragrance_that_similar_id'], unique=False)
    op.create_index('ix_similar fragrance_fragrance_id', 'similar fragrance', ['fragrance_id'], unique=False)
    op.drop_index(op.f('ix_similar_fragrance_user_id'), table_name='similar_fragrance')
    op.drop_index(op.f('ix_similar_fragrance_fragrance_that_similar_id'), table_name='similar_fragrance')
    op.drop_index(op.f('ix_similar_fragrance_fragrance_id'), table_name='similar_fragrance')
    op.drop_table('similar_fragrance')
    # ### end Alembic commands ###
