"""add wishlist

Revision ID: 670d143d2509
Revises: 709698877f50
Create Date: 2025-05-20 19:44:42.872498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670d143d2509'
down_revision: Union[str, None] = '709698877f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fragrance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('OWNED', 'WANTED', 'USED', name='wishlisttype'), nullable=False),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fragrance_id', name='unique_user_fragrance')
    )
    op.create_index(op.f('ix_user_fragrance_fragrance_id'), 'user_fragrance', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_user_fragrance_user_id'), 'user_fragrance', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_fragrance_user_id'), table_name='user_fragrance')
    op.drop_index(op.f('ix_user_fragrance_fragrance_id'), table_name='user_fragrance')
    op.drop_table('user_fragrance')
    # ### end Alembic commands ###
