"""add season to fragrance models fragrance

Revision ID: 6a514c329533
Revises: 4937a4ff634d
Create Date: 2025-06-06 23:29:43.846298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a514c329533'
down_revision: Union[str, None] = '4937a4ff634d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragrance season',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.Enum('winter', 'spring', 'summer', 'fall', name='season'), nullable=False),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragrance season_fragrance_id'), 'fragrance season', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_fragrance season_user_id'), 'fragrance season', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fragrance season_user_id'), table_name='fragrance season')
    op.drop_index(op.f('ix_fragrance season_fragrance_id'), table_name='fragrance season')
    op.drop_table('fragrance season')
    # ### end Alembic commands ###
