"""fix reviews

Revision ID: 709698877f50
Revises: 2007e34f7c06
Create Date: 2025-05-18 20:09:02.239057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709698877f50'
down_revision: Union[str, None] = '2007e34f7c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('fragrance_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_reviews_fragrance_id'), 'reviews', ['fragrance_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'fragrance', ['fragrance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_fragrance_id'), table_name='reviews')
    op.drop_column('reviews', 'fragrance_id')
    # ### end Alembic commands ###
