"""Add url field to my_table

Revision ID: 7f38c749b8bc
Revises: 7f3d2c07fddd
Create Date: 2025-05-11 21:19:58.574978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f38c749b8bc'
down_revision: Union[str, None] = '7f3d2c07fddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fragrance', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fragrance', 'picture')
    # ### end Alembic commands ###
