"""add many-to-many relationship

Revision ID: 91a1b3c6fad8
Revises: 70028ba7c411
Create Date: 2025-05-13 18:17:33.827850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a1b3c6fad8'
down_revision: Union[str, None] = '70028ba7c411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragrance_accords_relationship',
    sa.Column('fragrance_id', sa.BigInteger(), nullable=False),
    sa.Column('accord_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['accord_id'], ['accord.id'], ),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.PrimaryKeyConstraint('fragrance_id', 'accord_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fragrance_accords_relationship')
    # ### end Alembic commands ###
