"""change name

Revision ID: ae2678a6ea79
Revises: 6a514c329533
Create Date: 2025-06-06 23:50:20.618529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae2678a6ea79'
down_revision: Union[str, None] = '6a514c329533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragrance_season',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fragrance_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.Enum('winter', 'spring', 'summer', 'fall', name='season'), nullable=False),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragrance_season_fragrance_id'), 'fragrance_season', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_fragrance_season_user_id'), 'fragrance_season', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
