"""add accord groups and change accords

Revision ID: aebdd05e6b89
Revises: 7f38c749b8bc
Create Date: 2025-05-11 22:12:49.494560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebdd05e6b89'
down_revision: Union[str, None] = '7f38c749b8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accord_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accord', sa.Column('group_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_accord_group_id'), 'accord', ['group_id'], unique=False)
    op.create_foreign_key(None, 'accord', 'accord_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accord', type_='foreignkey')
    op.drop_index(op.f('ix_accord_group_id'), table_name='accord')
    op.drop_column('accord', 'group_id')
    op.drop_table('accord_group')
    # ### end Alembic commands ###
