"""add ml to fragrance

Revision ID: b080a7c96212
Revises: c236a6c093ae
Create Date: 2025-04-19 23:47:10.151671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b080a7c96212'
down_revision: Union[str, None] = 'c236a6c093ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fragrance', sa.Column('ml', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fragrance', 'ml')
    # ### end Alembic commands ###
