"""initial

Revision ID: c236a6c093ae
Revises: 
Create Date: 2025-04-17 23:05:00.049933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c236a6c093ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fragrance', sa.Column('price', sa.Integer(), nullable=True))
    # 1. First, explicitly create the ENUM type
    op.execute("CREATE TYPE fragrancetype AS ENUM ('edp', 'elixir', 'par', 'edt')")


    # 2. Then, add the column using the already-created type
    op.add_column('fragrance', sa.Column('fragrance_type', sa.Enum(name='fragrancetype'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE fragrancetype")


    # ### end Alembic commands ###
