"""edit models

Revision ID: df4f224911de
Revises: 924b2c20c48e
Create Date: 2025-04-13 21:33:04.134032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4f224911de'
down_revision: Union[str, None] = '924b2c20c48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accord',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('company', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('company', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('fragrance', sa.Column('company_id', sa.BigInteger(), nullable=False))
    op.alter_column('fragrance', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.create_foreign_key(None, 'fragrance', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fragrance', type_='foreignkey')
    op.alter_column('fragrance', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('fragrance', 'company_id')
    op.alter_column('company', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('company', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_table('accord')
    # ### end Alembic commands ###
